# Generated by Django 5.2.7 on 2026-02-25 06:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Complaint Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("head", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.CharField(max_length=30)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("WEB", "Web Portal"),
                            ("SMS", "SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sender_name", models.CharField(max_length=200)),
                (
                    "sender_contact",
                    models.CharField(
                        blank=True,
                        help_text="Email address or phone number",
                        max_length=200,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_no",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: CCPCR-YYYY-LTR/CMP-NNNN",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("LETTER", "Letter"), ("COMPLAINT", "Complaint")],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                (
                    "sender_name",
                    models.CharField(
                        help_text="Sender for letters, Citizen name for complaints",
                        max_length=200,
                    ),
                ),
                (
                    "sender_contact",
                    models.CharField(
                        blank=True, help_text="Phone or email", max_length=200
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REPLIED", "Replied"),
                            ("FORWARDED", "Forwarded"),
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Full details / body"),
                ),
                ("notes", models.TextField(blank=True, help_text="Internal remarks")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department this is forwarded/assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diary_no",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: CCPCR-YYYY-LTR-NNNN",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "letter_type",
                    models.CharField(
                        blank=True, help_text="Optional subcategory", max_length=100
                    ),
                ),
                ("reply_due_date", models.DateField(blank=True, null=True)),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter",
                        to="core.masterrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_line", models.CharField(max_length=500)),
                ("summary", models.TextField(help_text="Brief summary of the draft")),
                ("body", models.TextField(help_text="Full draft content")),
                (
                    "ai_suggestion",
                    models.TextField(
                        blank=True, help_text="AI-generated improvement suggestion"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="core.masterrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("description", models.CharField(max_length=300)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="core.masterrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_no",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated: CCPCR-YYYY-CMP-NNNN",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("victim_age", models.IntegerField(blank=True, null=True)),
                (
                    "victim_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.complaintcategory",
                    ),
                ),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint",
                        to="core.masterrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="Officer", max_length=100)),
                ("initials", models.CharField(blank=True, max_length=5)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="masterrecord",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.staffprofile",
            ),
        ),
        migrations.CreateModel(
            name="ForwardRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forwarded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "forwarded_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forwards",
                        to="core.masterrecord",
                    ),
                ),
                (
                    "forwarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-forwarded_at"],
            },
        ),
    ]
