# Generated by Django 6.0.2 on 2026-02-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "CCPCR Admin"), ("DEPT_USER", "Department User")],
                default="DEPT_USER",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Reply content / action taken")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "forward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.forwardrecord",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.masterrecord",
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.staffprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Replies",
                "ordering": ["-created_at"],
            },
        ),
    ]
