# Generated by Django 6.0.2 on 2026-02-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_staffprofile_role_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterrecord",
            name="filed_against",
            field=models.CharField(
                blank=True,
                help_text="Who the letter/complaint is filed against (person, organization, etc.)",
                max_length=255,
            ),
        ),
    ]
